# compose.yml

version: '3'
services:
  cypress:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: npm run cy:run
    # environment:
    #   - NODE_ENV=development
    # ports:
    #   - "8080:8080"  # We can adjust ports as necessary
    # depends_on:
    #   - backend  # If we have a backend service, otherwise we can remove this line
