name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run -- --spec "cypress/e2e/UI/SwagLabsUI/**/*.ts"

      - name: Upload Cypress screenshots and videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: cypress/screenshots

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: cypress/videos
