name: API TEST Pipeline

trigger:
  - none

pr:
  - none

stages:
  - stage: CypressTestsAPI
    displayName: Running Cypress Tests
    jobs:
      - job: RunAPITests
        timeoutInMinutes: 360
        pool:
          name: //poolname
          demands:
          - agent.name -equals //name
        displayName: Running API Tests
        steps: 
          - task: NodeTool@0
            inputs:
              versionSpec: '19.x'
          - script: |
              powershell npm install
              powershell npx cypress run --spec "cypress/e2e/API/**/*.ts" --headless
              powershell -Command npm run apireport
              powershell -Command npm run combine:junitapireports
          - task: PublishTestResults@2
            displayName: Publishing API Junit report
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(Build.SourcesDirectory)\cypress\junit-reports\junit-api-report.xml'
          - script: |
              mkdir $(Build.SourcesDirectory)/mochawesome-report-api/ 
              powershell -Command Copy-Item -Path $(Build.SourcesDirectory)\cypress\screenshots\ -Destination $(Build.SourcesDirectory)\mochawesome-report-api -recurse -Force
              powershell -Command Copy-Item -Path $(Build.SourcesDirectory)\cypress\videos\ -Destination $(Build.SourcesDirectory)\mochawesome-report-api -recurse -Force
              powershell -Command Copy-Item -Path $(Build.SourcesDirectory)\cypress\reports\ -Destination $(Build.SourcesDirectory)\mochawesome-report-api -recurse -Force
          - task: ArchiveFiles@2
            displayName: Compressing Files
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)/mochawesome-report-api
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: mochawesome-report-api.zip
          - task: PublishPipelineArtifact@1
            displayName: Publishing HTML test report
            inputs:
              publishLocation: 'pipeline'
              artifact: mochawesome-report-api.zip
              targetPath: $(Build.SourcesDirectory)\mochawesome-report-api.zip
